In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('scraped_df.csv')

In [3]:
df.shape

(10678, 47)

In [4]:
#making all columns lowercase and replace white spaces with _
df.columns = df.columns.str.replace(' ', '_').str.lower()

In [5]:
#Every stat with the "last" prefix means that its a stat from the previous season
df.columns

Index(['full_name', 'date_of_birth', 'place_of_birth', 'age', 'height',
       'citizenship', 'position', 'foot', 'player_agent', 'current_club',
       'joined', 'contract_expires', 'date_of_last_contract_extension',
       'outfitter', 'social_media', 'current_season', 'appearances', 'goals',
       'yellow', 'second_yellow', 'red', 'goals_conceded', 'clean_sheets',
       'minutes_played', 'last_appearances', 'last_goals', 'last_yellow',
       'last_second_yellow', 'last_red', 'last_goals_conceded',
       'last_clean_sheets', 'last_minutes_played', 'short_name', 'league',
       'league_country', 'latest_market_value', 'highest_market_value',
       'name_in_home_country', 'on_loan_from', 'contract_there_expires',
       'assists', 'last_assists', 'main_position', 'secondary_position',
       '2th_club', 'contract_option', '3th_club'],
      dtype='object')

In [6]:
#using columns that will be usefull to our eda and our model
df = df[['short_name', 'latest_market_value', 'highest_market_value','current_club',
         'position', 'main_position', 'secondary_position',  'age', 'height','citizenship', 'league_country'
         ,'foot', 'player_agent', 'outfitter',  'league', 'on_loan_from', 'contract_expires',
         'appearances', 'goals', 'assists','yellow', 'second_yellow', 'red', 'minutes_played','goals_conceded',
         'clean_sheets','last_appearances', 'last_goals', 'last_yellow','last_second_yellow','last_red', 
         'last_goals_conceded', 'last_clean_sheets', 'last_assists','last_minutes_played']]

In [7]:
df.head()

,short_name,latest_market_value,highest_market_value,current_club,position,main_position,secondary_position,age,height,citizenship,...,clean_sheets,last_appearances,last_goals,last_yellow,last_second_yellow,last_red,last_goals_conceded,last_clean_sheets,last_assists,last_minutes_played
0,Ederson,$61.60m,$77.00m,Manchester City,Goalkeeper,NaN,NaN,27.0,"1,88 m",Brazil Portugal,...,20,55.0,-,3,-,-,38,28,NaN,4.980'
1,Zack Steffen,$6.60m,$11.00m,Manchester City,Goalkeeper,NaN,NaN,25.0,"1,91 m",United States,...,2,13.0,-,-,-,-,17,4,NaN,1.170'
2,Arijanet Muric,$1.98m,$2.20m,Manchester City,Goalkeeper,NaN,NaN,21.0,"1,98 m",Kosovo Montenegro,...,1,7.0,-,-,-,-,2,5,NaN,660'
3,Claudio Bravo,$1.32m,$16.50m,Manchester City,Goalkeeper,NaN,NaN,37.0,"1,84 m",Chile Spain,...,5,1.0,-,-,-,-,-,1,NaN,90'
4,Scott Carson,$880Th.,$6.60m,Manchester City,Goalkeeper,NaN,NaN,34.0,"1,88 m",England,...,-,33.0,-,1,-,-,45,6,NaN,2.970'

In [8]:
to_numeric_cols = ['appearances', 'goals', 'yellow', 'second_yellow', 
    'red', 'goals_conceded', 'clean_sheets', 'last_appearances', 'last_goals', 
    'last_yellow', 'last_second_yellow', 'last_red', 'last_goals_conceded', 'last_clean_sheets', 
    'assists', 'last_assists', 'minutes_played', 'last_minutes_played', 'contract_expires']

In [9]:
df[to_numeric_cols] = df[to_numeric_cols].replace('-',0)

#since we will be using this list to convert columns to int type columns, we need to remove the date column
to_numeric_cols.remove('contract_expires')

In [10]:
df.shape

(10678, 35)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10678 entries, 0 to 10677
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   short_name            10678 non-null  object
 1   latest_market_value   9842 non-null   object
 2   highest_market_value  9842 non-null   object
 3   current_club          10678 non-null  object
 4   position              10678 non-null  object
 5   main_position         9340 non-null   object
 6   secondary_position    7575 non-null   object
 7   age                   10664 non-null  float64
 8   height                10015 non-null  object
 9   citizenship           10678 non-null  object
 10  league_country        10678 non-null  object
 11  foot                  9292 non-null   object
 12  player_agent          8375 non-null   object
 13  outfitter             1744 non-null   object
 14  league                10678 non-null  object
 15  on_loan_from          463 non-null    object
 16  contract_expires      10678 non-null  object
 17  appearances           10147 non-null  object
 18  goals                 10147 non-null  object
 19  assists               9018 non-null   object
 20  yellow                10147 non-null  object
 21  second_yellow         10147 non-null  object
 22  red                   10147 non-null  object
 23  minutes_played        10147 non-null  object
 24  goals_conceded        1129 non-null   object
 25  clean_sheets          1129 non-null   object
 26  last_appearances      9888 non-null   object
 27  last_goals            9888 non-null   object
 28  last_yellow           9888 non-null   object
 29  last_second_yellow    9888 non-null   object
 30  last_red              9888 non-null   object
 31  last_goals_conceded   1103 non-null   object
 32  last_clean_sheets     1103 non-null   object
 33  last_assists          8785 non-null   object
 34  last_minutes_played   9888 non-null   object
dtypes: float64(1), object(34)
memory usage: 2.9+ MB

In [12]:
df['citizenship'].unique()

array(['Brazil\xa0\xa0Portugal', 'United States',
       'Kosovo\xa0\xa0Montenegro', 'Chile\xa0\xa0Spain', 'England',
       'France', "Netherlands\xa0\xa0Cote d'Ivoire", 'Spain', 'Argentina',
       'Netherlands', 'England\xa0\xa0Nigeria', 'France\xa0\xa0Senegal',
       'Ukraine', 'Portugal', 'Brazil', 'Venezuela', 'Croatia', 'Germany',
       'Belgium', 'Serbia', 'Japan', 'England\xa0\xa0Jamaica', 'Colombia',
       'Algeria\xa0\xa0France', 'Argentina\xa0\xa0Spain', 'Ireland',
       'Netherlands\xa0\xa0Suriname', 'England\xa0\xa0The Gambia',
       'Cameroon\xa0\xa0Germany', 'Scotland', 'Greece', 'Wales', 'Guinea',
       'Wales\xa0\xa0England', 'Senegal', 'Egypt',
       'Switzerland\xa0\xa0Kosovo', 'Belgium\xa0\xa0Kenya', 'Nigeria',
       'Germany\xa0\xa0Sierra Leone',
       'France\xa0\xa0Central African Republic', 'Denmark',
       'England\xa0\xa0Canada', 'Italy\xa0\xa0Brazil', 'Ghana', 'Italy',
       "France\xa0\xa0Cote d'Ivoire", 'France\xa0\xa0Mali',
       'United States\xa0\xa0Croatia', 'England\xa0\xa0Ghana',
       'Morocco\xa0\xa0Netherlands', 'Belgium\xa0\xa0DR Congo',
       'Argentina\xa0\xa0Italy', 'Portugal\xa0\xa0Switzerland', 'Sweden',
       "Cote d'Ivoire", 'England\xa0\xa0DR Congo',
       'England\xa0\xa0Angola', 'Netherlands\xa0\xa0Ghana',
       'Serbia\xa0\xa0Slovakia', 'Scotland\xa0\xa0England',
       'Brazil\xa0\xa0Belgium', 'France\xa0\xa0Guadeloupe',
       'Nigeria\xa0\xa0Italy', 'United States\xa0\xa0England',
       'England\xa0\xa0Portugal', 'France\xa0\xa0DR Congo',
       'Denmark\xa0\xa0France', 'Portugal\xa0\xa0Sao Tome and Principe',
       'Korea, South', 'North Macedonia\xa0\xa0England',
       'France\xa0\xa0Cameroon', 'Germany\xa0\xa0Albania',
       'Scotland\xa0\xa0Isle of Man', 'Bosnia-Herzegovina\xa0\xa0Germany',
       'Portugal\xa0\xa0Germany', 'Uruguay\xa0\xa0Spain', 'Switzerland',
       'France\xa0\xa0Morocco', 'England\xa0\xa0Montserrat',
       'Brazil\xa0\xa0Italy', "Cote d'Ivoire\xa0\xa0France",
       'England\xa0\xa0Zimbabwe', 'Gabon\xa0\xa0France',
       'Switzerland\xa0\xa0Bosnia-Herzegovina', 'Turkey',
       'Northern Ireland', 'Jamaica\xa0\xa0England', 'Austria',
       'Portugal\xa0\xa0Cape Verde', 'England\xa0\xa0Bangladesh',
       'Portugal\xa0\xa0France', 'Mali\xa0\xa0France', 'Algeria',
       'England\xa0\xa0Ireland', 'France\xa0\xa0Congo',
       'England\xa0\xa0Guyana', 'DR Congo\xa0\xa0England', 'Iceland',
       'Nigeria\xa0\xa0England', 'Brazil\xa0\xa0Spain',
       "Italy\xa0\xa0Cote d'Ivoire", 'Turkey\xa0\xa0Germany',
       'Montenegro\xa0\xa0England', 'Morocco\xa0\xa0France',
       'Portugal\xa0\xa0Brazil', 'England\xa0\xa0Scotland',
       'Ireland\xa0\xa0England', 'Spain\xa0\xa0Mali', 'Mexico',
       'Ecuador\xa0\xa0Spain', 'Poland', 'Ireland\xa0\xa0United States',
       'Paraguay', 'Italy\xa0\xa0Nigeria', 'DR Congo\xa0\xa0France',
       'Czech Republic', 'England\xa0\xa0Wales', 'Norway',
       'England\xa0\xa0Barbados', 'England\xa0\xa0Bermuda', 'Zimbabwe',
       'Netherlands\xa0\xa0Morocco', 'Tanzania',
       'Australia\xa0\xa0England', 'Ireland\xa0\xa0Northern Ireland',
       'Romania', "Mali\xa0\xa0Cote d'Ivoire",
       'Australia\xa0\xa0Netherlands', 'Colombia\xa0\xa0England', 'Iran',
       'France\xa0\xa0Argentina', 'Romania\xa0\xa0Spain',
       'Denmark\xa0\xa0Germany', 'France\xa0\xa0Tunisia', 'Mali',
       'England\xa0\xa0Antigua and Barbuda', 'Ireland\xa0\xa0Nigeria',
       'Slovakia', 'United States\xa0\xa0Latvia', 'England\xa0\xa0Turkey',
       'Senegal\xa0\xa0France', 'Italy\xa0\xa0Morocco',
       'England\xa0\xa0Sierra Leone', 'Portugal\xa0\xa0Guinea-Bissau',
       'Colombia\xa0\xa0Spain', 'Netherlands\xa0\xa0Curacao',
       'Senegal\xa0\xa0Belgium', 'Ireland\xa0\xa0Scotland',
       'Ghana\xa0\xa0Germany', 'England\xa0\xa0Cameroon',
       "Cote d'Ivoire\xa0\xa0England", 'Ghana\xa0\xa0France',
       'England\xa0\xa0Northern Ireland', 'Denmark\xa0\xa0Nigeria',
       'England\xa0\xa0Switzerland', 'Netherlands\xa0\xa0Nigeria',
       'England\xa0\xa0St. Lucia', 'Northern Ireland\xa0\xa0England',
       'England\xa0\xa0Poland', 'New Zealand', 'England\xa0\xa0Spain',
       'Switzerland\xa0\xa0Germany', 'France\xa0\xa0Togo',
       'Germany\xa0\xa0Austria', 'Cuba\xa0\xa0Germany',
       'Luxembourg\xa0\xa0Serbia', 'Finland',
       'Switzerland\xa0\xa0Croatia', 'United States\xa0\xa0Chile',
       'England\xa0\xa0Greece', 'France\xa0\xa0Martinique',
       'Morocco\xa0\xa0Spain', 'Spain\xa0\xa0Morocco',
       'Spain\xa0\xa0Netherlands', 'France\xa0\xa0Algeria',
       'Dominican Republic\xa0\xa0Spain', 'France\xa0\xa0French Guiana',
       'Uruguay', 'Spain\xa0\xa0Dominican Republic',
       'Croatia\xa0\xa0Switzerland', 'Chile',
       'Spain\xa0\xa0Guinea-Bissau', 'Uruguay\xa0\xa0Italy',
       'Denmark\xa0\xa0Guyana', 'Slovenia', 'Montenegro\xa0\xa0Serbia',
       'Mexico\xa0\xa0Portugal', 'Belgium\xa0\xa0Spain',
       'Spain\xa0\xa0Lithuania', 'Spain\xa0\xa0Brazil',
       'France\xa0\xa0Guinea', 'France\xa0\xa0Belgium',
       'Central African Republic\xa0\xa0France', 'Russia\xa0\xa0Spain',
       'Belgium\xa0\xa0Kosovo', 'Sweden\xa0\xa0Eritrea',
       'France\xa0\xa0Benin', 'France\xa0\xa0Italy',
       'Serbia\xa0\xa0Netherlands', 'Morocco', 'Spain\xa0\xa0Ghana',
       'Bosnia-Herzegovina\xa0\xa0Spain', 'Portugal\xa0\xa0Angola',
       'Mexico\xa0\xa0Spain', 'Cameroon', 'Togo',
       'Cameroon\xa0\xa0France', 'Scotland\xa0\xa0Spain',
       'Peru\xa0\xa0Netherlands', 'Denmark\xa0\xa0Southern Sudan',
       'Turkey\xa0\xa0Denmark', 'Spain\xa0\xa0Argentina', 'China',
       'Costa Rica\xa0\xa0Spain', 'Martinique\xa0\xa0France',
       'Montenegro', 'North Macedonia\xa0\xa0Albania',
       'Benin\xa0\xa0France', 'Panama', 'Angola\xa0\xa0Portugal',
       'Guadeloupe\xa0\xa0France', 'Cameroon\xa0\xa0Spain',
       'Venezuela\xa0\xa0Spain', 'Mauritania', 'Senegal\xa0\xa0Spain',
       'North Macedonia', 'Peru', 'Bosnia-Herzegovina\xa0\xa0Luxembourg',
       'Germany\xa0\xa0Tunisia', 'Argentina\xa0\xa0France', 'Albania',
       'Germany\xa0\xa0Italy', 'Germany\xa0\xa0Lebanon',
       'Sweden\xa0\xa0Denmark', 'Brazil\xa0\xa0Uruguay',
       'Italy\xa0\xa0Canada', 'Armenia', 'Bosnia-Herzegovina',
       'Bosnia-Herzegovina\xa0\xa0Canada', 'France\xa0\xa0Spain',
       'Switzerland\xa0\xa0Chile', 'Sweden\xa0\xa0Bosnia-Herzegovina',
       'Belgium\xa0\xa0Italy', 'Angola', 'Denmark\xa0\xa0Albania',
       'Serbia\xa0\xa0Spain', 'Netherlands\xa0\xa0Jamaica',
       'Bosnia-Herzegovina\xa0\xa0Switzerland',
       'Albania\xa0\xa0Switzerland', 'Germany\xa0\xa0Netherlands',
       'The Gambia', 'Slovenia\xa0\xa0Croatia',
       'Netherlands\xa0\xa0Indonesia', 'Ghana\xa0\xa0Italy', 'Estonia',
       'Moldova\xa0\xa0Romania', 'Belgium\xa0\xa0Indonesia', 'Bulgaria',
       'Kosovo\xa0\xa0Albania', 'Brazil\xa0\xa0Serbia',
       'Turkey\xa0\xa0Austria', 'Germany\xa0\xa0United States',
       'Equatorial Guinea\xa0\xa0Spain', 'Albania\xa0\xa0Italy',
       'Sweden\xa0\xa0Italy', 'Sweden\xa0\xa0North Macedonia',
       'Senegal\xa0\xa0Italy', 'Canada\xa0\xa0Norway',
       'Italy\xa0\xa0Germany', 'Germany\xa0\xa0France',
       'England\xa0\xa0Guinea-Bissau', 'Germany\xa0\xa0Turkey',
       'Italy\xa0\xa0Ghana', 'Italy\xa0\xa0Colombia',
       'North Macedonia\xa0\xa0Italy', 'Paraguay\xa0\xa0Spain',
       'Nigeria\xa0\xa0Netherlands', 'Bosnia-Herzegovina\xa0\xa0Croatia',
       'Sweden\xa0\xa0DR Congo', 'Italy\xa0\xa0Venezuela',
       'Albania\xa0\xa0Sweden', 'Poland\xa0\xa0Brazil',
       'Burkina Faso\xa0\xa0France', 'Italy\xa0\xa0Peru',
       'Canada\xa0\xa0Liberia', 'Germany\xa0\xa0Brazil',
       "Germany\xa0\xa0Cote d'Ivoire", 'Germany\xa0\xa0Kosovo',
       'Switzerland\xa0\xa0Nigeria', 'Belgium\xa0\xa0Martinique',
       'Denmark\xa0\xa0United States', 'Germany\xa0\xa0Syria',
       'United States\xa0\xa0Portugal', 'Germany\xa0\xa0Cameroon',
       'Hungary', 'Switzerland\xa0\xa0Cameroon',
       'France\xa0\xa0Guinea-Bissau', 'Hungary\xa0\xa0Germany',
       'Germany\xa0\xa0Togo', 'Germany\xa0\xa0Ghana',
       'Denmark\xa0\xa0Tanzania', 'France\xa0\xa0Haiti',
       'Finland\xa0\xa0Slovakia', 'Burkina Faso', 'Austria\xa0\xa0Serbia',
       'Germany\xa0\xa0Afghanistan', 'Jamaica', 'Germany\xa0\xa0Morocco',
       'Switzerland\xa0\xa0DR Congo', 'England\xa0\xa0Germany',
       'Guinea\xa0\xa0France', 'Germany\xa0\xa0Nigeria',
       'Netherlands\xa0\xa0Tunisia', 'Germany\xa0\xa0Hungary',
       'Germany\xa0\xa0Serbia', 'Germany\xa0\xa0Croatia', 'Australia',
       'Israel', 'Serbia\xa0\xa0Bosnia-Herzegovina',
       'Togo\xa0\xa0Germany', 'United States\xa0\xa0Germany',
       'Croatia\xa0\xa0Germany', 'Switzerland\xa0\xa0North Macedonia',
       'Egypt\xa0\xa0Canada', 'Germany\xa0\xa0Angola',
       'Switzerland\xa0\xa0Senegal', 'Angola\xa0\xa0Germany',
       "Morocco\xa0\xa0Cote d'Ivoire", 'Morocco\xa0\xa0Germany',
       'Serbia\xa0\xa0Switzerland', 'Czech Republic\xa0\xa0Ethiopia',
       'Bulgaria\xa0\xa0Germany', 'Ecuador', 'Austria\xa0\xa0Germany',
       'Germany\xa0\xa0Russia', 'Switzerland\xa0\xa0Dominican Republic',
       'Nigeria\xa0\xa0Germany', 'Israel\xa0\xa0Portugal',
       'Germany\xa0\xa0England', 'Netherlands\xa0\xa0St. Kitts & Nevis',
       'Germany\xa0\xa0DR Congo', 'Austria\xa0\xa0Kenya',
       'Switzerland\xa0\xa0Portugal', 'Luxembourg\xa0\xa0Portugal',
       'Sweden\xa0\xa0Ghana', 'Tunisia\xa0\xa0Germany',
       'Australia\xa0\xa0Italy', 'Serbia\xa0\xa0Germany',
       'Tunisia\xa0\xa0France', 'Germany\xa0\xa0Senegal',
       'Norway\xa0\xa0United States', 'Germany\xa0\xa0Georgia',
       'Germany\xa0\xa0Poland', 'Poland\xa0\xa0Germany',
       'Japan\xa0\xa0Germany', 'Greece\xa0\xa0Germany',
       'France\xa0\xa0Philippines', 'Brazil\xa0\xa0France',
       'France\xa0\xa0Poland', 'Germany\xa0\xa0Burundi',
       'Netherlands\xa0\xa0Spain', 'Netherlands\xa0\xa0Mozambique',
       'Brazil\xa0\xa0Netherlands', "England\xa0\xa0Cote d'Ivoire",
       'France\xa0\xa0Burkina Faso', 'Guinea-Bissau\xa0\xa0Portugal',
       'Russia', 'Belgium\xa0\xa0Morocco', 'France\xa0\xa0Netherlands',
       'Netherlands\xa0\xa0DR Congo', 'Spain\xa0\xa0Congo', 'Mozambique',
       'Mexico\xa0\xa0Italy', 'Canada\xa0\xa0United States',
       'France\xa0\xa0Comoros', 'United States\xa0\xa0France',
       'Comoros\xa0\xa0France', 'Argentina\xa0\xa0Mexico',
       'Senegal\xa0\xa0Guinea-Bissau', 'France\xa0\xa0Portugal',
       'France\xa0\xa0Angola', 'France\xa0\xa0United States',
       'France\xa0\xa0The Gambia', 'Switzerland\xa0\xa0Spain',
       'France\xa0\xa0Ghana', 'France\xa0\xa0Serbia',
       'France\xa0\xa0Rwanda', 'Serbia\xa0\xa0Slovenia',
       'Russia\xa0\xa0France', 'South Africa', 'Serbia\xa0\xa0Montenegro',
       "Cote d'Ivoire\xa0\xa0Italy", 'Chad', 'France\xa0\xa0Mauritania',
       'Bosnia-Herzegovina\xa0\xa0France', 'France\xa0\xa0Croatia',
       'France\xa0\xa0Madagascar', 'Austria\xa0\xa0Croatia',
       'Kosovo\xa0\xa0Norway', 'Kosovo\xa0\xa0Sweden',
       'Switzerland\xa0\xa0Angola', 'Greece\xa0\xa0England', 'Luxembourg',
       'France\xa0\xa0Chad', 'Cape Verde', 'French Guiana\xa0\xa0France',
       'Italy\xa0\xa0Argentina', 'France\xa0\xa0Malta',
       'France\xa0\xa0Cape Verde', 'Trinidad and Tobago\xa0\xa0England',
       'France\xa0\xa0RÃ©union', 'DR Congo', 'Paraguay\xa0\xa0Argentina',
       'Togo\xa0\xa0France', 'France\xa0\xa0Gabon', 'Iran\xa0\xa0Sweden',
       'Sweden\xa0\xa0Zambia', 'Spain\xa0\xa0Senegal', 'Gabon',
       'Cape Verde\xa0\xa0France', 'Belgium\xa0\xa0Serbia',
       'Switzerland\xa0\xa0The Gambia', 'Cape Verde\xa0\xa0Portugal',
       'Portugal\xa0\xa0England', 'Libya', 'England\xa0\xa0Pakistan',
       "Burkina Faso\xa0\xa0Cote d'Ivoire", 'Netherlands\xa0\xa0Liberia',
       'England\xa0\xa0Cyprus', 'Cape Verde\xa0\xa0Netherlands',
       'Iraq\xa0\xa0Netherlands', 'El Salvador',
       'Argentina\xa0\xa0United States', 'Brazil\xa0\xa0Germany',
       'Cameroon\xa0\xa0Brazil', 'Venezuela\xa0\xa0Argentina',
       'Canada\xa0\xa0Portugal', 'Honduras', 'Moldova\xa0\xa0Portugal',
       'Portugal\xa0\xa0Canada', 'Netherlands\xa0\xa0Portugal',
       'Portugal\xa0\xa0Senegal', 'Georgia',
       'Guinea-Bissau\xa0\xa0Senegal', 'Guinea-Bissau',
       'Brazil\xa0\xa0Poland', 'Russia\xa0\xa0Brazil',
       'Russia\xa0\xa0Georgia', 'Russia\xa0\xa0Kyrgyzstan',
       'Russia\xa0\xa0Armenia', 'Belarus', 'Belarus\xa0\xa0Russia',
       'Netherlands\xa0\xa0Angola', 'Czech Republic\xa0\xa0Slovakia',
       'Russia\xa0\xa0Azerbaijan', 'Uzbekistan',
       'Sweden\xa0\xa0Cape Verde', 'Russia\xa0\xa0Finland',
       'Russia\xa0\xa0Germany', 'Russia\xa0\xa0Kazakhstan', 'Lithuania',
       'Bosnia-Herzegovina\xa0\xa0Sweden', 'Finland\xa0\xa0Russia',
       'Kazakhstan', 'Switzerland\xa0\xa0Serbia',
       'Kazakhstan\xa0\xa0Russia', 'Russia\xa0\xa0Ukraine',
       'Venezuela\xa0\xa0Colombia', 'Georgia\xa0\xa0Russia',
       'Germany\xa0\xa0Kazakhstan', 'Zambia', 'Russia\xa0\xa0Tajikistan',
       'Switzerland\xa0\xa0Italy', 'Slovenia\xa0\xa0Argentina', 'Iraq',
       'Moldova\xa0\xa0Russia', 'Russia\xa0\xa0Belarus',
       'Russia\xa0\xa0Italy', 'Russia\xa0\xa0Nigeria',
       'Russia\xa0\xa0Moldova', 'Armenia\xa0\xa0Germany',
       'United States\xa0\xa0Netherlands', 'Netherlands\xa0\xa0Aruba',
       'Netherlands\xa0\xa0Congo',
       'Netherlands\xa0\xa0Dominican Republic',
       'New Zealand\xa0\xa0England', 'Netherlands\xa0\xa0Togo',
       'Greece\xa0\xa0Netherlands', 'Turkey\xa0\xa0Netherlands',
       'Bosnia-Herzegovina\xa0\xa0Denmark', 'Germany\xa0\xa0The Gambia',
       'Netherlands\xa0\xa0Greece', 'Australia\xa0\xa0Iran',
       'Sweden\xa0\xa0Lebanon', 'Netherlands\xa0\xa0Turkey',
       'Albania\xa0\xa0England', 'Curacao\xa0\xa0Netherlands',
       'Belgium\xa0\xa0Burundi', 'Netherlands\xa0\xa0Italy',
       'Morocco\xa0\xa0Belgium', 'Australia\xa0\xa0Bosnia-Herzegovina',
       'Netherlands\xa0\xa0Brazil', 'Netherlands\xa0\xa0United States',
       'Albania\xa0\xa0Belgium', 'Netherlands\xa0\xa0Algeria',
       'Sweden\xa0\xa0Russia', 'Finland\xa0\xa0Netherlands',
       'Netherlands\xa0\xa0Albania', 'Iran\xa0\xa0Netherlands',
       'Greece\xa0\xa0Albania', 'Germany\xa0\xa0Greece',
       'Sweden\xa0\xa0Norway', 'Belgium\xa0\xa0Ghana',
       'Portugal\xa0\xa0Luxembourg', 'Netherlands\xa0\xa0Senegal',
       'Netherlands\xa0\xa0Cape Verde', 'Netherlands\xa0\xa0Colombia',
       'Peru\xa0\xa0Spain', "Belgium\xa0\xa0Cote d'Ivoire",
       'Belgium\xa0\xa0Senegal', 'United States\xa0\xa0Spain',
       'Burundi\xa0\xa0Belgium', 'Hungary\xa0\xa0Serbia',
       'Chinese Taipei (Taiwan)\xa0\xa0Spain',
       'Bosnia-Herzegovina\xa0\xa0Netherlands',
       'Switzerland\xa0\xa0Netherlands', 'Netherlands\xa0\xa0Germany',
       'Netherlands\xa0\xa0Korea, South',
       'Czech Republic\xa0\xa0Netherlands', 'Israel\xa0\xa0Argentina',
       'Belgium\xa0\xa0Austria', 'Netherlands\xa0\xa0Russia',
       'United States\xa0\xa0Hungary', 'Belgium\xa0\xa0Algeria',
       'Angola\xa0\xa0Belgium', 'Bosnia-Herzegovina\xa0\xa0Serbia',
       'Belgium\xa0\xa0Haiti', 'United States\xa0\xa0Israel',
       'Sierra Leone', 'Australia\xa0\xa0Serbia',
       'Belgium\xa0\xa0Nigeria', 'Kosovo', 'Nigeria\xa0\xa0Belgium',
       'Belgium\xa0\xa0Guinea-Bissau', 'Belgium\xa0\xa0Poland',
       'Belgium\xa0\xa0Bosnia-Herzegovina', 'Ukraine\xa0\xa0Bulgaria',
       'Ghana\xa0\xa0Belgium', 'DR Congo\xa0\xa0Netherlands',
       'Egypt\xa0\xa0Saudi Arabia', 'Cyprus', 'Kosovo\xa0\xa0Belgium',
       'Belgium\xa0\xa0Guinea', 'Belgium\xa0\xa0Chad',
       'Israel\xa0\xa0Belgium', 'Belgium\xa0\xa0Angola',
       'Sweden\xa0\xa0Belgium', 'Madagascar\xa0\xa0France',
       'Togo\xa0\xa0Belgium', 'Italy\xa0\xa0Cameroon',
       'Trinidad and Tobago', 'Belgium\xa0\xa0Turkey',
       'Sweden\xa0\xa0Tunisia', 'Belgium\xa0\xa0Brazil',
       'Australia\xa0\xa0Greece', 'Tunisia', 'Burundi\xa0\xa0England',
       'Haiti\xa0\xa0France', 'DR Congo\xa0\xa0Belgium',
       'Serbia\xa0\xa0Croatia', 'Malaysia', 'Belgium\xa0\xa0France',
       'Congo\xa0\xa0Belgium', 'Italy\xa0\xa0Belgium',
       'Albania\xa0\xa0Germany', 'Nigeria\xa0\xa0Spain',
       'France\xa0\xa0Moldova', 'Canada\xa0\xa0France',
       'Canada\xa0\xa0Belgium', 'Kenya\xa0\xa0Belgium',
       'Belgium\xa0\xa0Albania', 'Bosnia-Herzegovina\xa0\xa0Slovenia',
       'Congo', 'Costa Rica', 'Rwanda', 'Morocco\xa0\xa0Portugal',
       'Turkey\xa0\xa0England', 'Turkey\xa0\xa0France',
       'Denmark\xa0\xa0The Gambia', 'Sweden\xa0\xa0Turkey',
       'Australia\xa0\xa0Turkey', 'Azerbaijan\xa0\xa0Turkey',
       'Brazil\xa0\xa0Bulgaria', 'Turkey\xa0\xa0Switzerland',
       'Canada\xa0\xa0Trinidad and Tobago',
       'United States\xa0\xa0New Zealand', 'Canada\xa0\xa0Jamaica',
       'Brazil\xa0\xa0Romania', 'Turkey\xa0\xa0Cyprus',
       'Turkey\xa0\xa0Australia',
       'North Macedonia\xa0\xa0Bosnia-Herzegovina',
       'Turkey\xa0\xa0Belgium', 'Uganda',
       'Bosnia-Herzegovina\xa0\xa0Belgium', 'Burundi',
       'Austria\xa0\xa0Turkey',
       'Bosnia-Herzegovina\xa0\xa0North Macedonia',
       'France\xa0\xa0Turkey', 'North Macedonia\xa0\xa0Austria',
       'Austria\xa0\xa0England', 'Austria\xa0\xa0Nigeria',
       'Austria\xa0\xa0Bosnia-Herzegovina',
       'The Gambia\xa0\xa0Guinea-Bissau',
       'Austria\xa0\xa0Dominican Republic', 'Austria\xa0\xa0Kosovo',
       'Austria\xa0\xa0Czech Republic', 'Switzerland\xa0\xa0Ghana',
       'Kosovo\xa0\xa0Austria', 'Austria\xa0\xa0Ghana',
       'Austria\xa0\xa0Tanzania', 'Croatia\xa0\xa0Austria',
       'Ukraine\xa0\xa0Brazil', "Nigeria\xa0\xa0Cote d'Ivoire",
       'Ukraine\xa0\xa0Georgia', 'Belgium\xa0\xa0Sierra Leone',
       'Germany\xa0\xa0Israel', 'Israel\xa0\xa0Ukraine', 'Latvia',
       'Azerbaijan\xa0\xa0Ukraine', 'Ukraine\xa0\xa0Hungary',
       'France\xa0\xa0Scotland', 'Greece\xa0\xa0Australia',
       'Greece\xa0\xa0Brazil', 'Egypt\xa0\xa0Portugal',
       'Albania\xa0\xa0Greece', 'Bosnia-Herzegovina\xa0\xa0United States',
       'Argentina\xa0\xa0Paraguay', 'Mauritius\xa0\xa0France',
       'Argentina\xa0\xa0Portugal', 'Israel\xa0\xa0Azerbaijan',
       'Spain\xa0\xa0England', 'Greece\xa0\xa0Syria',
       'Algeria\xa0\xa0England', 'United States\xa0\xa0Nigeria',
       'Serbia\xa0\xa0Greece', 'Greece\xa0\xa0Czech Republic', 'Bolivia',
       'Poland\xa0\xa0Greece', 'Mauritania\xa0\xa0France',
       'Croatia\xa0\xa0Bosnia-Herzegovina', 'Zimbabwe\xa0\xa0England',
       'Switzerland\xa0\xa0Albania', 'Finland\xa0\xa0Sierra Leone',
       'Canada\xa0\xa0Scotland', 'Romania\xa0\xa0Turkey',
       'Wales\xa0\xa0Scotland', 'Northern Ireland\xa0\xa0Scotland',
       'Uganda\xa0\xa0England', 'Scotland\xa0\xa0Ireland',
       'Cyprus\xa0\xa0Serbia', 'Australia\xa0\xa0Scotland',
       'Scotland\xa0\xa0France', 'Scotland\xa0\xa0United States',
       'South Africa\xa0\xa0Scotland', 'Scotland\xa0\xa0Algeria',
       'Northern Ireland\xa0\xa0Ireland', 'Scotland\xa0\xa0Italy',
       'Canada\xa0\xa0England', 'Congo\xa0\xa0France',
       'England\xa0\xa0Italy', 'Scotland\xa0\xa0Nigeria',
       'New Zealand\xa0\xa0Scotland', 'Canada\xa0\xa0Poland',
       'Scotland\xa0\xa0Wales', 'Greece\xa0\xa0Nigeria',
       'Switzerland\xa0\xa0Cape Verde', 'Albania\xa0\xa0North Macedonia',
       'Switzerland\xa0\xa0Turkey', 'Angola\xa0\xa0France',
       'Switzerland\xa0\xa0Philippines', 'Kosovo\xa0\xa0Switzerland',
       'Switzerland\xa0\xa0Austria', 'Switzerland\xa0\xa0Brazil',
       'Switzerland\xa0\xa0Ethiopia', 'Tunisia\xa0\xa0Switzerland',
       "Switzerland\xa0\xa0Cote d'Ivoire", 'Switzerland\xa0\xa0Tunisia',
       'Switzerland\xa0\xa0Greece', 'Switzerland\xa0\xa0France',
       'DR Congo\xa0\xa0Switzerland', 'Switzerland\xa0\xa0Congo',
       'Switzerland\xa0\xa0Kenya', 'Liechtenstein', 'Germany\xa0\xa0Iraq',
       'PalÃ¤stina\xa0\xa0Switzerland', 'Nigeria\xa0\xa0Switzerland',
       'Austria\xa0\xa0Slovenia', 'Switzerland\xa0\xa0Bolivia',

In [13]:
#Get the citizenship
s = df['citizenship'].str.split(u'\xa0', n=3, expand=True)
df['country'], df['country_2'] = s[0], s[2]
df.drop(columns = ['citizenship'], inplace = True, axis = 1)

In [14]:
df.country.unique()

array(['Brazil', 'United States', 'Kosovo', 'Chile', 'England', 'France',
       'Netherlands', 'Spain', 'Argentina', 'Ukraine', 'Portugal',
       'Venezuela', 'Croatia', 'Germany', 'Belgium', 'Serbia', 'Japan',
       'Colombia', 'Algeria', 'Ireland', 'Cameroon', 'Scotland', 'Greece',
       'Wales', 'Guinea', 'Senegal', 'Egypt', 'Switzerland', 'Nigeria',
       'Denmark', 'Italy', 'Ghana', 'Morocco', 'Sweden', "Cote d'Ivoire",
       'Korea, South', 'North Macedonia', 'Bosnia-Herzegovina', 'Uruguay',
       'Gabon', 'Turkey', 'Northern Ireland', 'Jamaica', 'Austria',
       'Mali', 'DR Congo', 'Iceland', 'Montenegro', 'Mexico', 'Ecuador',
       'Poland', 'Paraguay', 'Czech Republic', 'Norway', 'Zimbabwe',
       'Tanzania', 'Australia', 'Romania', 'Iran', 'Slovakia',
       'New Zealand', 'Cuba', 'Luxembourg', 'Finland',
       'Dominican Republic', 'Slovenia', 'Central African Republic',
       'Russia', 'Togo', 'Peru', 'China', 'Costa Rica', 'Martinique',
       'Benin', 'Panama', 'Angola', 'Guadeloupe', 'Mauritania', 'Albania',
       'Armenia', 'The Gambia', 'Estonia', 'Moldova', 'Bulgaria',
       'Equatorial Guinea', 'Canada', 'Burkina Faso', 'Hungary', 'Israel',
       'Tunisia', 'Guinea-Bissau', 'Mozambique', 'Comoros',
       'South Africa', 'Chad', 'Cape Verde', 'French Guiana',
       'Trinidad and Tobago', 'Libya', 'Iraq', 'El Salvador', 'Honduras',
       'Georgia', 'Belarus', 'Uzbekistan', 'Lithuania', 'Kazakhstan',
       'Zambia', 'Curacao', 'Burundi', 'Chinese Taipei (Taiwan)',
       'Sierra Leone', 'Cyprus', 'Madagascar', 'Haiti', 'Malaysia',
       'Congo', 'Kenya', 'Rwanda', 'Azerbaijan', 'Uganda', 'Latvia',
       'Mauritius', 'Bolivia', 'Liechtenstein', 'PalÃ¤stina', 'Niger',
       'Faroe Islands', 'Liberia', 'Bahrain', 'Lebanon', 'Saudi Arabia',
       'Indonesia', 'Afghanistan', 'Eritrea', 'Syria', 'Jordan',
       'Suriname', 'Andorra', 'Kyrgyzstan', 'Turkmenistan', 'Tajikistan'],
      dtype=object)

In [15]:
df.country_2.unique()

array(['Portugal', None, 'Montenegro', 'Spain', "Cote d'Ivoire",
       'Nigeria', 'Senegal', 'Jamaica', 'France', 'Suriname',
       'The Gambia', 'Germany', 'England', 'Kosovo', 'Kenya',
       'Sierra Leone', 'Central African Republic', 'Canada', 'Brazil',
       'Mali', 'Croatia', 'Ghana', 'Netherlands', 'DR Congo', 'Italy',
       'Switzerland', 'Angola', 'Slovakia', 'Belgium', 'Guadeloupe',
       'Sao Tome and Principe', 'Cameroon', 'Albania', 'Isle of Man',
       'Morocco', 'Montserrat', 'Zimbabwe', 'Bosnia-Herzegovina',
       'Cape Verde', 'Bangladesh', 'Ireland', 'Congo', 'Guyana',
       'Scotland', 'United States', 'Wales', 'Barbados', 'Bermuda',
       'Northern Ireland', 'Argentina', 'Tunisia', 'Antigua and Barbuda',
       'Latvia', 'Turkey', 'Guinea-Bissau', 'Curacao', 'St. Lucia',
       'Poland', 'Togo', 'Austria', 'Serbia', 'Chile', 'Greece',
       'Martinique', 'Algeria', 'French Guiana', 'Dominican Republic',
       'Lithuania', 'Guinea', 'Eritrea', 'Benin', 'Southern Sudan',
       'Denmark', 'Luxembourg', 'Lebanon', 'Uruguay', 'Indonesia',
       'Romania', 'North Macedonia', 'Norway', 'Colombia', 'Venezuela',
       'Sweden', 'Peru', 'Liberia', 'Syria', 'Tanzania', 'Haiti',
       'Afghanistan', 'Hungary', 'Ethiopia', 'Russia',
       'St. Kitts & Nevis', 'Georgia', 'Philippines', 'Burundi',
       'Mozambique', 'Burkina Faso', 'Comoros', 'Mexico', 'Rwanda',
       'Slovenia', 'Mauritania', 'Madagascar', 'Chad', 'Malta',
       'RÃ©union', 'Gabon', 'Zambia', 'Pakistan', 'Cyprus', 'Kyrgyzstan',
       'Armenia', 'Azerbaijan', 'Finland', 'Kazakhstan', 'Ukraine',
       'Tajikistan', 'Belarus', 'Moldova', 'Aruba', 'Iran',
       'Korea, South', 'Israel', 'Bulgaria', 'Saudi Arabia',
       'Trinidad and Tobago', 'New Zealand', 'Australia',
       'Czech Republic', 'Paraguay', 'Iraq', 'Bolivia', 'Dominica',
       'Malaysia', 'PalÃ¤stina', 'Namibia', 'Vietnam', 'Thailand',
       'Somalia', 'Iceland', 'Jordan', 'South Africa', 'Uzbekistan',
       'Turkmenistan', 'Sudan'], dtype=object)

In [16]:
#Converting string type currency to a float
df['latest_value_letter'] = df['latest_market_value'].str.extract('([A-Za-z]+)')
df['latest_market_value'] = df['latest_market_value'].str.extract(r'(\d+.\d+)').astype('float')
df['latest_market_value'] = df.apply(lambda x: x.latest_market_value * 1000 if x.latest_value_letter == 'Th' else x.latest_market_value * 1000000, axis = 1)
df.drop(columns = 'latest_value_letter', inplace = True, axis = 1)

df['highest_value_letter'] = df['highest_market_value'].str.extract('([A-Za-z]+)')
df['highest_market_value'] = df['highest_market_value'].str.extract(r'(\d+.\d+)').astype('float')
df['highest_market_value'] = df.apply(lambda x: x.highest_market_value * 1000 if x.highest_value_letter == 'Th' else x.highest_market_value * 1000000, axis = 1)
df.drop(columns = 'highest_value_letter', inplace = True, axis = 1)

In [17]:
df[['latest_market_value', 'highest_market_value']]

       latest_market_value  highest_market_value
0               61600000.0            77000000.0
1                6600000.0            11000000.0
2                1980000.0             2200000.0
3                1320000.0            16500000.0
4                 880000.0             6600000.0
...                    ...                   ...
10673                  NaN              165000.0
10674                  NaN              275000.0
10675             330000.0              330000.0
10676                  NaN                   NaN
10677             275000.0              275000.0

[10678 rows x 2 columns]

In [18]:
# % of null values in columns
df.isnull().mean().sort_values()

short_name              0.000000
current_club            0.000000
position                0.000000
country                 0.000000
league_country          0.000000
contract_expires        0.000000
league                  0.000000
age                     0.001311
minutes_played          0.049728
red                     0.049728
second_yellow           0.049728
yellow                  0.049728
appearances             0.049728
goals                   0.049728
height                  0.062090
last_second_yellow      0.073984
last_yellow             0.073984
last_red                0.073984
last_minutes_played     0.073984
last_goals              0.073984
last_appearances        0.073984
highest_market_value    0.109665
latest_market_value     0.124087
main_position           0.125304
foot                    0.129800
assists                 0.155460
last_assists            0.177280
player_agent            0.215677
secondary_position      0.290597
country_2               0.776925
outfitter               0.836674
clean_sheets            0.894269
goals_conceded          0.894269
last_goals_conceded     0.896704
last_clean_sheets       0.896704
on_loan_from            0.956640
dtype: float64

In [19]:
#Filtering out rows from columns that can't have nan values
df = df[df['latest_market_value'].notna()]
df = df[df['league'].notna()]

In [20]:
#Filling columns with mode
df['foot'] = df['foot'].fillna(df['foot'].mode()[0])

In [21]:
#Height to float and filling NAs with the height mean
df['height'] = df['height'].str.extract(r'(\d+.\d+)')
df['height'] = df['height'].str.replace(',','.').astype('float')
df['height'] = df['height'].fillna(df['height'].mean())

In [22]:
#If there's information 1 else 0
df[['on_loan_from','secondary_position', 'country_2']] = df[['on_loan_from','secondary_position','country_2']].where(df[['on_loan_from', 'secondary_position','country_2']].isnull(), 1).fillna(0).astype(int)

In [23]:
#Filling with unknown where you can't fill with any other value such as mean and mode
df[['outfitter','player_agent']] = df[['outfitter','player_agent']].fillna('unknown')

In [24]:
df.isnull().mean().sort_values()

short_name              0.000000
country                 0.000000
contract_expires        0.000000
on_loan_from            0.000000
league                  0.000000
outfitter               0.000000
player_agent            0.000000
foot                    0.000000
league_country          0.000000
country_2               0.000000
age                     0.000000
secondary_position      0.000000
height                  0.000000
position                0.000000
current_club            0.000000
highest_market_value    0.000000
latest_market_value     0.000000
red                     0.030472
second_yellow           0.030472
minutes_played          0.030472
appearances             0.030472
yellow                  0.030472
goals                   0.030472
last_appearances        0.032931
last_goals              0.032931
last_yellow             0.032931
last_second_yellow      0.032931
last_red                0.032931
last_minutes_played     0.032931
main_position           0.105100
assists                 0.130974
last_assists            0.133005
goals_conceded          0.899497
clean_sheets            0.899497
last_goals_conceded     0.899925
last_clean_sheets       0.899925
dtype: float64

In [25]:
#Removing time string from minutes played columns
df['minutes_played'] = df['minutes_played'].str.replace('.','').str.replace("'","")
df['last_minutes_played'] = df['last_minutes_played'].str.replace('.','').str.replace("'","")

In [26]:
#Filling NAs in the numeric cols with 0
df[to_numeric_cols] = df[to_numeric_cols].fillna(0)

In [27]:
#convert all numeric column to an integer type column
for i in to_numeric_cols:
    try:
        df[i] = df[i].astype(int)
    except ValueError:
        df[i] = df[i].astype('float').astype(int)

In [28]:
#Converting columns to date types
df['contract_expires'] = pd.to_datetime(df['contract_expires'], errors = 'ignore')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9353 entries, 0 to 10677
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   short_name            9353 non-null   object
 1   latest_market_value   9353 non-null   float64
 2   highest_market_value  9353 non-null   float64
 3   current_club          9353 non-null   object
 4   position              9353 non-null   object
 5   main_position         8370 non-null   object
 6   secondary_position    9353 non-null   int32
 7   age                   9353 non-null   float64
 8   height                9353 non-null   float64
 9   league_country        9353 non-null   object
 10  foot                  9353 non-null   object
 11  player_agent          9353 non-null   object
 12  outfitter             9353 non-null   object
 13  league                9353 non-null   object
 14  on_loan_from          9353 non-null   int32
 15  contract_expires      9353 non-null   object
 16  appearances           9353 non-null   int32
 17  goals                 9353 non-null   int32
 18  assists               9353 non-null   int32
 19  yellow                9353 non-null   int32
 20  second_yellow         9353 non-null   int32
 21  red                   9353 non-null   int32
 22  minutes_played        9353 non-null   int32
 23  goals_conceded        9353 non-null   int32
 24  clean_sheets          9353 non-null   int32
 25  last_appearances      9353 non-null   int32
 26  last_goals            9353 non-null   int32
 27  last_yellow           9353 non-null   int32
 28  last_second_yellow    9353 non-null   int32
 29  last_red              9353 non-null   int32
 30  last_goals_conceded   9353 non-null   int32
 31  last_clean_sheets     9353 non-null   int32
 32  last_assists          9353 non-null   int32
 33  last_minutes_played   9353 non-null   int32
 34  country               9353 non-null   object
 35  country_2             9353 non-null   int32
dtypes: float64(4), int32(21), object(11)
memory usage: 1.9+ MB

In [30]:
df.isnull().mean().sort_values()

short_name              0.0000
second_yellow           0.0000
red                     0.0000
minutes_played          0.0000
goals_conceded          0.0000
clean_sheets            0.0000
last_appearances        0.0000
yellow                  0.0000
last_goals              0.0000
last_second_yellow      0.0000
last_red                0.0000
last_goals_conceded     0.0000
last_clean_sheets       0.0000
last_assists            0.0000
last_minutes_played     0.0000
last_yellow             0.0000
assists                 0.0000
goals                   0.0000
appearances             0.0000
latest_market_value     0.0000
highest_market_value    0.0000
current_club            0.0000
position                0.0000
secondary_position      0.0000
age                     0.0000
country                 0.0000
height                  0.0000
foot                    0.0000
player_agent            0.0000
outfitter               0.0000
league                  0.0000
on_loan_from            0.0000
contract_expires        0.0000
league_country          0.0000
country_2               0.0000
main_position           0.1051
dtype: float64

Keepers will never have a main position, since their only position is GoalKeeper. But, there are a few players that don't have a main position because of a mistake from the website or because the website could not get the player's main position. As you can see in the cell bellow, it's an irrelevant % of the observations, so we're just going to remove it.

In [31]:
print('''% of observations that are not keepers and have null "main position" : {}'''.format((len(df[(df['position'] != 'Goalkeeper') & (df['main_position'].isnull())]) / len(df))))

% of observations that are not keepers and have null "main position" : 0.0013899283652304075

In [32]:
#Removing the rows that match this condition
df = df.drop(df[(df['position'] != 'Goalkeeper') & (df['main_position'].isnull())].index)

In [33]:
#Filling the null values in the main_position column with goalkeeper since all of those rows are keepers data
df['main_position'] = df.apply(lambda x: 'Goalkeeper' if x.position == 'Goalkeeper' else x.main_position, axis = 1)

Now I'm going to rename leagues that have the same name, but are from different countries, since <a href = "https://www.transfermarkt.us/"> transfer market</a> gives the same name to the German Bundesliga and the austrian Bundesliga for example.

In [34]:
#creating dataframe with duplicated leagues
duplicated_leagues = df.groupby(['league', 'league_country']).count().reset_index()[['league','league_country']]
duplicated_leagues['duplicated'] = duplicated_leagues.groupby(['league']).transform('count')
duplicated_leagues = duplicated_leagues[duplicated_leagues['duplicated'] > 1]['league'].unique()
duplicated_leagues

array(['Bundesliga', 'Premier Liga'], dtype=object)

In [35]:
#If is duplicated then concatenate with country name
df['league'] = df.apply(lambda x: x.league if x.league not in duplicated_leagues else x.league + "_" + x.league_country, axis = 1)

In [36]:
df.to_csv('cleaned_df.csv')